/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   MINILIB.h                                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jbayona- <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/09/11 19:54:55 by jbayona-          #+#    #+#             */
/*   Updated: 2023/11/23 19:21:45 by jbayona-         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef MINILIB_H
# define MINILIB_H

#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdarg.h>

int print_c(int c)
int print_s(char *str)
int print_digit(long n, int base)
int print_digit(long n, int base)
#endif